Blog app - integration specs for views and fix n+1 problems
gsmalik030/myblog-app pull request #9
Opened 2023-05-16 08:26 UTC by gsmalik030

### In This pull request I :

- [x] Solved The n+1 problems when fetching all posts and their comments for a user.
- [x] Used Capybara to write integration tests for each view.
- [x] Tested the views : User index page,user show page,User post index page,Post show page.

2023-05-16 13:26 UTC, addod19 commented
### Hi @gsmalik030, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is invalid because, you worked on the project alone whilst it should have been a pair programming activity. **NB**: You will have to wait for student success to give you the go ahead before any code reviewer can review it as solo. Also, once you are approved by student success, kindly take a screenshot of the email you receive and attach it to the PR for verification

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-17 08:38 UTC, Davidosky007 requested changes
Hi @gsmalik030 @Mukumbuta 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
* Integration tests written properly 👍 
* Good looking readme 👍 
* No linter errors 👍 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @davidsoky007 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-17 08:38 UTC, Davidosky007 commented on Gemfile
> +gem 'bullet'
* As stated in the requirements, you are not to use the bullet gem for solving N+1 problems, kindly remove the gem, solve the N+1 issues and add a screenshot of your result to your PR 
![image](https://github.com/gsmalik030/myblog-app/assets/52497246/38c3a72d-31c9-4600-8b49-21890defef6a)

2023-05-17 09:15 UTC, addod19 requested changes
### Hi @gsmalik030 and @Mukumbuta, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- [ ] Nice job addressing the previous comment by removing the `bullet` gem from the Gemfile :rocket: 


 ## Required Changes ♻️
_Check the comments under the review._
- [ ] It would be better if we add the screenshot of the app's logs before and after fixing the N+1 query problem. Currently, we have a screenshot of the code, and that is not what we are required to add to the PR. Here is the screenshot of the project requirements
![Screenshot from 2023-05-17 09-01-09](https://github.com/gsmalik030/myblog-app/assets/46388113/25968eb8-2a9d-466d-b302-14a1ee450d56)


## Optional suggestions
- [ ] Going forward, let us improve our commit messages, we can write `Fix` instead of `Fixed`, `Add` instead of `add`, etc

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-17 09:15 UTC, addod19 commented on spec/integration/post_spec.rb
> +                          posts_counter: 0)
- [ ] It would be better if all our test cases pass, currently we have 2 of the test failing. Let us kindly address them as seen in the screenshot below
![Screenshot from 2023-05-17 09-07-29](https://github.com/gsmalik030/myblog-app/assets/46388113/53b10ef7-5beb-4d48-968d-cecefa87bf8b)

2023-05-17 09:24 UTC, gsmalik030 commented on spec/integration/post_spec.rb
> +                          posts_counter: 0)
Hello @addod19 
When I am running tests all are passing

<img width="929" alt="image" src="https://github.com/gsmalik030/myblog-app/assets/114066191/d027efa4-27d6-4cb2-af4d-31e172c8bf0a">

can you give me a suggestion what could be the problem please

2023-05-17 09:32 UTC, addod19 commented on spec/integration/post_spec.rb
> +                          posts_counter: 0)
@gsmalik030 , I have run it a few times but i still encounter the errors, but for now kindly fix the other comment about the logs of the N+1 query problem. Maybe other code reviewers will not have the same issue

2023-05-17 11:55 UTC, julie-ify approved these changes
Hi @gsmalik030 and @Mukumbuta,

## Highlights!
- Good code organization and working app ✔️
- Descriptive README ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Status: Approved ✔️ 

Cheers and Happy coding!👏👏👏

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-17 11:59 UTC, merged